AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
  - bin/*
  - polyanalyst6api.gemspec
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Naming/AccessorMethodName:
  Enabled: false
