AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
  - bin/*
  - polyanalyst6api.gemspec
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
