AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
  - bin/*
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Metrics/LineLength:
  Max: 100 # TODO: get it to 85
Metrics/ClassLength:
  Enabled: false
